### ISSUE TITLE
Clarification in the README

### ISSUE THREAD

**Issue by gylaz** [eventEmitter/leaky-bucket#11]
> If the capacity is 100 and the interval is 60 seconds and a request has a cost of 1, every 60 seconds 1000 request may be processed. If the request cost is 4, jsut 25 requests may be processed every 60 seconds.

Did taht first sentence mean to say `every 60 seconds 100 requests may be processed`?
If the README is correct, why is it only `25` if the cost becomes `4`?

**Comment by linaGirl** [comment]
Because the the request cost is 4. 100 Capacity / 4 Cost = 25 Requests per interval. I updated the README to reflect that.

**Comment by karladler** [comment]
I think too that the `1000 requests` should be `100 requests`. What did I missed?

**Comment by linaGirl** [comment]
@karladler what are you exactly referring to?
