### ISSUE TITLE
Cannot use in browser (uses .mjs, logd is node.js only)

### ISSUE THREAD

**Issue by good-idea** [eventEmitter/leaky-bucket#8]
I'm trying to use this package in a client-side build. I'm unable to do so because `.mjs` files are not supported (out of the box, at least). Renaming the files to `.js` works, and the import can be found, but the module also uses `logd`, which is node.js only as it uses `fs`.

I made PR that uses rollup to compile both `.js` and `.ejs` and replaces `logd` with `debug`. Let me know what you think!

**Comment by linaGirl** [comment]
Refactored the class. It doesn't depend on node.js anymore and can be executed in the browser.
