### ISSUE TITLE
First wave of requests breaks the bucket

### ISSUE THREAD

**Issue by glagola** [eventEmitter/leaky-bucket#9]
Hi, I have such config: 
```js
new LeakyBucket({
    capacity: 1000,
    interval: 60,
    timeout: 300,
})
```
Version of the leaky-bucket package I use: v3.0.4

The API server returns wasted cost on each request. Each request has 50 points cost (`await bucket.throttle(50)`). For some reason first wave of my requests break the leaky bucket, remote API server returns 1500 wasted points and I'm getting ban. If the service doesn't ban me, then the bucket starts to work properly and the remote API returns wasted points stays below `capacity` all the rest time.

I'm not sure how to write a test for the case. But I found a workaround, right after LeakyBucket creation I pay full `capacity` points and it start to work as it is expected:

```js
const capacity = 1000;
const bucket =  new LeakyBucket({
    capacity,
    interval: 60,
    timeout: 300,
});

bucket.pay(capacity); // if you remove this line the remote api service will ban you

(async () => {
    for (let i = 0; i < 5000; ++i) {
        await bucket.throttle(50);
        const response = await fetch(...)
    }
})();
```
P.S. sorry for my English

**Comment by linaGirl** [comment]
hi @glagola 

Sorry for the very late reply. This is actually the correct behaviour of a leaky bucket. The bucket gets emptied until it's at zero capacity without throttling at all. The bucket won't throttle as long as there is capacity left. In your test case, it will execute 20 requests (1000 capacity / 50 cost  = 20 requests) instantaneously and then execute a request every 3 seconds thereafter (1000 capacity / 60 seconds fill rate =  16.6 capacity refill / second, e.g 3 seconds per 50 capacity (16.6 * 3 = 50). 

The problem may be: the other side doesn't continually fill up the bucket but just at the end of the interval. You are thus emptying the bucket and sending more requests while the other side expects you to wait the full 60 seconds for refilling the bucket. 

I may implement a feature for this behaviour, if there is demand for it. Please add a :+1: to this comment, if you'd like me to implement this.

**Comment by linaGirl** [comment]
I added the `initalCapacity` option to the constructor, which basically does the same as your call to the pay() method. See the readme for mode information.
